<?xml version="1.0" ?>
<!DOCTYPE championship [
        <!ELEMENT championship (event)*>
        <!ELEMENT event (data|action|response)*>
        <!ATTLIST event
                meth CDATA #REQUIRED
                part CDATA #REQUIRED
                time CDATA #REQUIRED>
        <!ELEMENT data (heading|men|contract|budget)*>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT men (#PCDATA)>
        <!ELEMENT contract (#PCDATA)>
        <!ATTLIST contract
                amount CDATA #REQUIRED
                resource CDATA #REQUIRED>
        <!ELEMENT budget (#PCDATA)>
        <!ELEMENT action (parameters|creek|people)*>
        <!ATTLIST action
                name CDATA #REQUIRED>
        <!ELEMENT parameters (#PCDATA)>
        <!ATTLIST parameters
                direction CDATA #IMPLIED
                resource CDATA #IMPLIED>
        <!ELEMENT response (extras)*>
        <!ATTLIST response
                cost CDATA #REQUIRED
                status CDATA #REQUIRED>
        <!ELEMENT extras (range|found|biomes|creeks|altitude|resources|amount)*>
        <!ELEMENT range (#PCDATA)>
        <!ELEMENT found (#PCDATA)>
        <!ELEMENT biomes (biome)*>
        <!ELEMENT biome (#PCDATA)>
        <!ATTLIST biome
                name CDATA #REQUIRED>
        <!ELEMENT creeks (creek)*>
        <!ELEMENT creek (#PCDATA)>
        <!ATTLIST creek
                name CDATA #IMPLIED>
        <!ELEMENT people (#PCDATA)>
        <!ELEMENT altitude (#PCDATA)>
        <!ELEMENT resources (resource)*>
        <!ELEMENT resource (#PCDATA)>
        <!ELEMENT amount (#PCDATA)>
        ]>
<championship>
  <event part="Engine" time="1451849519994" meth="initialize">
    <data>
      <heading>S</heading>
      <men>25</men>
      <contract amount="100" resource="GLASS"/>
      <contract amount="5000" resource="WOOD"/>
      <contract amount="80" resource="FLOWER"/>
      <budget>10000</budget>
    </data>
  </event>
  <event part="Explorer" time="1451849520036" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520036" meth="takeDecision">
    <response status="OK" cost="7">
      <extras>
        <range>52</range>
        <found>OUT_OF_RANGE</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520046" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520047" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>52</range>
        <found>OUT_OF_RANGE</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520049" meth="takeDecision">
    <action name="echo">
      <parameters direction="W"/>
    </action>
  </event>
  <event part="Engine" time="1451849520049" meth="takeDecision">
    <response status="OK" cost="5">
      <extras>
        <range>0</range>
        <found>OUT_OF_RANGE</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520050" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520050" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520052" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520052" meth="takeDecision">
    <response status="OK" cost="4">
      <extras>
        <range>52</range>
        <found>OUT_OF_RANGE</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520054" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520054" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520055" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520055" meth="takeDecision">
    <response status="OK" cost="3">
      <extras>
        <range>52</range>
        <found>OUT_OF_RANGE</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520057" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520057" meth="takeDecision">
    <response status="OK" cost="2"></response>
  </event>
  <event part="Explorer" time="1451849520058" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520058" meth="takeDecision">
    <response status="OK" cost="3">
      <extras>
        <range>22</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520063" meth="takeDecision">
    <action name="heading">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520064" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520064" meth="takeDecision">
    <action name="scan"></action>
  </event>
  <event part="Engine" time="1451849520065" meth="takeDecision">
    <response status="OK" cost="5">
      <extras>
        <biomes>
          <biome name="OCEAN"/>
        </biomes>
        <creeks></creeks>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520067" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520067" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>20</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520069" meth="takeDecision">
    <action name="echo">
      <parameters direction="N"/>
    </action>
  </event>
  <event part="Engine" time="1451849520069" meth="takeDecision">
    <response status="OK" cost="4">
      <extras>
        <range>4</range>
        <found>OUT_OF_RANGE</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520070" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520071" meth="takeDecision">
    <response status="OK" cost="7">
      <extras>
        <range>48</range>
        <found>OUT_OF_RANGE</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520073" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520073" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520074" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520076" meth="takeDecision">
    <response status="OK" cost="4">
      <extras>
        <range>48</range>
        <found>OUT_OF_RANGE</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520078" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520078" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520080" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520080" meth="takeDecision">
    <response status="OK" cost="5">
      <extras>
        <range>19</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520082" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520082" meth="takeDecision">
    <response status="OK" cost="3"></response>
  </event>
  <event part="Explorer" time="1451849520083" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520084" meth="takeDecision">
    <response status="OK" cost="4">
      <extras>
        <range>15</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520085" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520085" meth="takeDecision">
    <response status="OK" cost="3"></response>
  </event>
  <event part="Explorer" time="1451849520086" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520086" meth="takeDecision">
    <response status="OK" cost="3">
      <extras>
        <range>6</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520088" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520088" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520089" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520089" meth="takeDecision">
    <response status="OK" cost="4">
      <extras>
        <range>5</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520091" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520091" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520092" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520092" meth="takeDecision">
    <response status="OK" cost="4">
      <extras>
        <range>5</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520094" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520094" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520095" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520096" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>4</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520099" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520099" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520100" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520101" meth="takeDecision">
    <response status="OK" cost="5">
      <extras>
        <range>4</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520102" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520103" meth="takeDecision">
    <response status="OK" cost="3"></response>
  </event>
  <event part="Explorer" time="1451849520104" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520104" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>6</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520106" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520106" meth="takeDecision">
    <response status="OK" cost="2"></response>
  </event>
  <event part="Explorer" time="1451849520107" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520107" meth="takeDecision">
    <response status="OK" cost="4">
      <extras>
        <range>6</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520110" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520110" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520111" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520111" meth="takeDecision">
    <response status="OK" cost="5">
      <extras>
        <range>5</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520113" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520113" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520115" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520115" meth="takeDecision">
    <response status="OK" cost="3">
      <extras>
        <range>6</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520117" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520117" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520118" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520119" meth="takeDecision">
    <response status="OK" cost="5">
      <extras>
        <range>6</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520120" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520120" meth="takeDecision">
    <response status="OK" cost="3"></response>
  </event>
  <event part="Explorer" time="1451849520121" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520122" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>7</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520123" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520124" meth="takeDecision">
    <response status="OK" cost="6"></response>
  </event>
  <event part="Explorer" time="1451849520125" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520125" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>8</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520127" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520127" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520128" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520128" meth="takeDecision">
    <response status="OK" cost="3">
      <extras>
        <range>9</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520130" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520130" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520130" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520130" meth="takeDecision">
    <response status="OK" cost="5">
      <extras>
        <range>8</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520132" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520132" meth="takeDecision">
    <response status="OK" cost="6"></response>
  </event>
  <event part="Explorer" time="1451849520133" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520133" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>8</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520135" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520135" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520136" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520136" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>9</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520138" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520138" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520149" meth="takeDecision">
    <action name="echo">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520150" meth="takeDecision">
    <response status="OK" cost="7">
      <extras>
        <range>2</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520153" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520153" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520155" meth="takeDecision">
    <action name="heading">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520155" meth="takeDecision">
    <response status="OK" cost="6"></response>
  </event>
  <event part="Explorer" time="1451849520157" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520157" meth="takeDecision">
    <response status="OK" cost="3"></response>
  </event>
  <event part="Explorer" time="1451849520159" meth="takeDecision">
    <action name="scan"></action>
  </event>
  <event part="Engine" time="1451849520159" meth="takeDecision">
    <response status="OK" cost="5">
      <extras>
        <biomes>
          <biome name="TROPICAL_SEASONAL_FOREST"/>
          <biome name="BEACH"/>
        </biomes>
        <creeks></creeks>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520170" meth="takeDecision">
    <action name="heading">
      <parameters direction="W"/>
    </action>
  </event>
  <event part="Engine" time="1451849520170" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520177" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520177" meth="takeDecision">
    <response status="OK" cost="3"></response>
  </event>
  <event part="Explorer" time="1451849520183" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520183" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520188" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520188" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520192" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520192" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520195" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520195" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520198" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520198" meth="takeDecision">
    <response status="OK" cost="2"></response>
  </event>
  <event part="Explorer" time="1451849520207" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520207" meth="takeDecision">
    <response status="OK" cost="6"></response>
  </event>
  <event part="Explorer" time="1451849520211" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520211" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520214" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520214" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520219" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520219" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520222" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520222" meth="takeDecision">
    <response status="OK" cost="2"></response>
  </event>
  <event part="Explorer" time="1451849520226" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520226" meth="takeDecision">
    <response status="OK" cost="3"></response>
  </event>
  <event part="Explorer" time="1451849520230" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520230" meth="takeDecision">
    <response status="OK" cost="3"></response>
  </event>
  <event part="Explorer" time="1451849520234" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520234" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520238" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520238" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520241" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520241" meth="takeDecision">
    <response status="OK" cost="2"></response>
  </event>
  <event part="Explorer" time="1451849520244" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520244" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520246" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520247" meth="takeDecision">
    <response status="OK" cost="6"></response>
  </event>
  <event part="Explorer" time="1451849520249" meth="takeDecision">
    <action name="heading">
      <parameters direction="S"/>
    </action>
  </event>
  <event part="Engine" time="1451849520249" meth="takeDecision">
    <response status="OK" cost="6"></response>
  </event>
  <event part="Explorer" time="1451849520253" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520254" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>17</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520257" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520257" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520260" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520260" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520263" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520263" meth="takeDecision">
    <response status="OK" cost="6"></response>
  </event>
  <event part="Explorer" time="1451849520266" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520266" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520268" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520269" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>1</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520271" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520271" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520274" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520274" meth="takeDecision">
    <response status="OK" cost="3">
      <extras>
        <range>2</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520277" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520277" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520280" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520280" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>1</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520285" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520285" meth="takeDecision">
    <response status="OK" cost="3"></response>
  </event>
  <event part="Explorer" time="1451849520288" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520288" meth="takeDecision">
    <response status="OK" cost="5">
      <extras>
        <range>1</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520291" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520291" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520294" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520294" meth="takeDecision">
    <response status="OK" cost="4">
      <extras>
        <range>2</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520297" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520297" meth="takeDecision">
    <response status="OK" cost="5"></response>
  </event>
  <event part="Explorer" time="1451849520300" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520300" meth="takeDecision">
    <response status="OK" cost="6">
      <extras>
        <range>1</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520301" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520302" meth="takeDecision">
    <response status="OK" cost="4"></response>
  </event>
  <event part="Explorer" time="1451849520303" meth="takeDecision">
    <action name="echo">
      <parameters direction="E"/>
    </action>
  </event>
  <event part="Engine" time="1451849520303" meth="takeDecision">
    <response status="OK" cost="5">
      <extras>
        <range>1</range>
        <found>GROUND</found>
      </extras>
    </response>
  </event>
  <event part="Explorer" time="1451849520306" meth="takeDecision">
    <action name="fly"></action>
  </event>
  <event part="Engine" time="1451849520306" meth="takeDecision">